# Publication-sized Makie defaults for figures generated by Documenter.
size_pt = (300, 180)
darkred = "#BB5566"
qudit_colors = (darkred, "#004488", "#DDAA33", "#228833")

theme = Theme(
    figure_padding=2,
    size=size_pt,
    fontsize=8,
    Lines=(
        linewidth=1.0,
    ),
    Scatter=(
        color=darkred,
        cycle=nothing,
        markersize=5.0,
        marker=:circle,
        strokewidth=0.3,
    ),
    Axis=(
        titlefont=:regular,
        titlesize=10,
        xlabelsize=10,
        ylabelsize=10,
        xgridvisible=false,
        ygridvisible=false,
        xticksize=2.5,
        yticksize=2.5,
        xminorticksize=1.5,
        yminorticksize=1.5,
        spinewidth=0.75,
        xtickwidth=0.75,
        ytickwidth=0.75,
    ),
    Legend=(
        labelfont=:regular,
        padding=(2, 2, 2, 2),
        patchlabelgap=5,
        patchsize=(9, 4),
        rowgap=2,
        colgap=8,
        titlefont=:regular,
        titlegap=3,
        margin=(2, 2, 2, 2),
        framevisible=false,
    ),
)

theme = merge(theme, theme_latexfonts())
update_theme!(theme)
CairoMakie.activate!(type = "svg", pt_per_unit=1.5)
