"""
    DestabilizerTableau(d::Int, n::Int; state::Symbol=:mixed, basis=:Z, storephase::Bool=true)
    DestabilizerTableau(d::Int, n::Int, state::Symbol; kwargs...)
    DestabilizerTableau(d::Int, tableau::AbstractMatrix{<:Integer}; m::Union{Int,Nothing}=nothing, storephase::Union{Bool,Nothing}=nothing)

Construct a destabilizer tableau for an `n`-qudit *stabilizer density operator*
(mixed-state stabilizer formalism).

This is the recommended tableau representation for most workflows. In addition
to the stabilizer generators, it maintains a dual destabilizer basis, enabling
fast span-membership tests, expectation values, and repeated measurements
without first canonicalizing the stabilizer generators.

# Arguments
- `d::Int`: Qudit dimension (must be a prime number).
- `n::Int`: Number of qudits (only for the `d, n` constructor).
- `state::Symbol`: Preset state for the positional `state` constructor.
- `tableau::AbstractMatrix{<:Integer}`: An integer stabilizer matrix in either
  `(2n + storephase) × m` or `m × (2n + storephase)` layout. The corresponding
  destabilizers are constructed automatically.

# Keyword Arguments
- `state::Symbol=:mixed`: Preset state (`:mixed`, `:product`, `:ghz`). Aliases
  `:X/:Y/:Z` map to `:product` in that basis.
- `basis=:Z`: Basis for product states (`:X`, `:Y`, `:Z`, or a per-qudit
  vector/tuple of Symbols).
- `storephase::Bool=true`: Whether to store the stabilizer phase row (for the
  `(d, n)` constructor). When constructing from a `tableau`, `storephase` is
  inferred from the matrix shape if not provided. Destabilizers never carry a
  phase row.
- `m::Union{Int,Nothing}=nothing`: Number of active stabilizer-generator columns
  (for the `(d, tableau)` constructor).
- `inversemod::InverseMod=PrecomputedInvMod(d)`: Inversion strategy used for
  phase calculations and construction of the dual basis.
- `check::Bool=true`: For the `(d, tableau)` constructor only, verify that the
  supplied generators commute and are independent, throwing `ArgumentError`
  naming the offending pair or the rank if they do not. The preset constructors
  satisfy both by construction and take no such keyword. `check=false` skips an
  `O(n^3)` validation and builds the tableau regardless -- every later operation
  then rests on a contract that may not hold, and `is_pure` will call such a
  tableau pure; `is_pure(tab; verify=true)` is what sees through it.

# Examples
```julia
tab = DestabilizerTableau(2, 3; state=:mixed)
tab = DestabilizerTableau(2, 3; state=:product, basis=:X)

raw = reshape(Int[0, 1, 0], 3, 1)
tab = DestabilizerTableau(2, raw)
```

# Notes
## Representation
The represented abelian stabilizer subgroup `S` is generated by `m` independent
commuting Paulis (`0 ≤ m ≤ n`). Both properties are contract: the raw-matrix
constructor enforces them (see `check`), the presets satisfy them by
construction, and `measure!` and [`canonicalize!`](@ref) preserve them. That is
what lets [`is_pure`](@ref) decide on `m == n` alone. Each active stabilizer `S_j` has a destabilizer
`D_j` satisfying the duality relation `⟨D_j, S_k⟩ = δ_jk` modulo `d`.

The internal stabilizer tableau has shape `(2n + storephase) × n`, while the
destabilizer matrix has shape `2n × n`.
- Only the **first `m` columns** are active stabilizer/destabilizer pairs.
- Columns `m+1:n` are unused (kept zero) and provide capacity for measurements
  that increase `m`.
- Construction from a raw matrix accepts stabilizers only and builds the dual
  destabilizers automatically.

## Phase convention
If `storephase=true`, the last stabilizer row stores the phase exponent `k`:
- odd prime `d`:  ω^k with k mod d
- d=2:            i^k with k mod 4

## Preset states
- `:mixed` (maximally mixed; `m=0`)
- `:product` (pure product state; `basis` is `:X`, `:Y`, `:Z`, or a vector/tuple of length `n`)
- `:ghz` (generalized GHZ on `n` qudits)

Use [`StabilizerTableau`](@ref) instead when compact storage is more important
than maintaining the dual basis. See also [`reset!`](@ref).
"""
mutable struct DestabilizerTableau{T<:InverseMod} <: AbstractTableau
    d::Int                             # qudit dimension
    n::Int                             # number of qudits
    m::Int                             # number of active generator columns (0 ≤ m ≤ n)
    stab::Matrix{Int}                 # tableau has dimensions (2n + storephase) × n
    destab::Matrix{Int}                # destabilizers: 2n × n (no phase row)
    storephase::Bool                   # whether phase information is stored
    iscanonical::Bool                  # true if the tableau is in canonical (RCEF) form
    inversemod::T                      # inverse mod function for dimension d

    # workspaces
    workspace::Matrix{Int}             # 2n×n (used by entanglement_entropy)
    generator_workspace::Vector{Int}   # length 2n + storephase

    # workspace for canonicalize!
    pivcol_of_row::Vector{Int}         # length 2n (pivot column for each row if canonical)
    xdotz_cache::Vector{Int}           # length n (stores x·z values for each generator)

    # workspace for expectation value calculations
    res_workspace::Vector{Int}         # length 2n
    c_workspace::Vector{Int}           # length n
    zacc_workspace::Vector{Int}        # length n

    # workspace for the noncommuting measurement update
    support_workspace::Vector{Int}     # length n (qudit support of one column)
end

function DestabilizerTableau(d::Int, n::Int;
    state::Symbol=:mixed,
    basis=:Z,
    storephase::Bool=true,
    inversemod::T=PrecomputedInvMod(d)
) where {T<:InverseMod}
    state_norm, basis_spec = _normalize_state_and_basis(state, basis, n)
    tab, m = _preset_tableau(d, n, state_norm, basis_spec, storephase)
    return _build_destabilizer_tableau(d, n, m, tab, storephase, inversemod;
                                       preset_state=state_norm, preset_basis=basis_spec)
end

DestabilizerTableau(d::Int, n::Int, state::Symbol; kwargs...) = DestabilizerTableau(d, n; state=state, kwargs...)

function DestabilizerTableau(d::Int, tableau::AbstractMatrix{<:Integer};
    m::Union{Int,Nothing}=nothing,
    storephase::Union{Bool,Nothing}=nothing,
    inversemod::T=PrecomputedInvMod(d),
    check::Bool=true
) where {T<:InverseMod}
    m !== nothing && m < 0 && throw(ArgumentError("m must satisfy 0 ≤ m ≤ n."))
    tab_in = (tableau isa Matrix{Int}) ? tableau : Matrix{Int}(tableau)
    layout = _infer_tableau_layout(size(tab_in, 1), size(tab_in, 2), m, storephase)
    layout === nothing && throw(ArgumentError(
        "Tableau must have shape (2n + storephase) × m or m × (2n + storephase) with m ≤ n."
    ))

    if layout.transpose
        tab_in = permutedims(tab_in)
    end

    return _build_destabilizer_tableau(d, layout.n, layout.m, tab_in, layout.storephase, inversemod;
                                      check=check)
end

function _build_destabilizer_tableau(
    d::Int,
    n::Int,
    m::Int,
    stab_in::AbstractMatrix{<:Integer},
    storephase::Bool,
    inversemod::T;
    preset_state::Union{Symbol,Nothing}=nothing,
    preset_basis=nothing,
    check::Bool=true,
) where {T<:InverseMod}
    !Primes.isprime(d) && throw(ArgumentError("Qudit dimension d must be a prime number."))
    (0 ≤ m ≤ n) || throw(ArgumentError("m must satisfy 0 ≤ m ≤ n."))
    _warn_if_dimension_unsafe(d, n)

    nrows = 2n + (storephase ? 1 : 0)
    size(stab_in, 1) == nrows || throw(ArgumentError("Tableau row count must be 2n (+1 if storephase=true)."))

    # We keep capacity n columns, but accept either n columns or m columns and pad.
    stab_in = (stab_in isa Matrix{Int}) ? stab_in : Matrix{Int}(stab_in)
    stab = if size(stab_in, 2) == n
        stab_in
    elseif size(stab_in, 2) == m
        tmp = zeros(Int, nrows, n)
        tmp[:, 1:m] .= stab_in
        tmp
    else
        throw(ArgumentError("Tableau must have either n columns (capacity) or m columns (active generators)."))
    end

    # A preset filler already writes reduced entries into a zeroed matrix, so
    # both passes below are pure overhead there -- and they are O(n^2) on a
    # matrix holding O(n) nonzeros.
    if preset_state === nothing
        # Reduce entries mod d / mod phase modulus
        @turbo for j in 1:n
            for i in 1:(2n)
                stab[i, j] = mod(stab[i, j], d)
            end
        end
        if storephase
            d_phase = phase_modulus(d)
            prow = 2n + 1
            @turbo for j in 1:n
                stab[prow, j] = mod(stab[prow, j], d_phase)
            end
        end

        # Ensure unused columns are zeroed.
        if m < n
            @turbo for j in (m+1):n, i in axes(stab, 1)
                stab[i, j] = 0
            end
        end
    end

    tab = DestabilizerTableau{T}(
        d,
        n,
        m,
        stab,
        zeros(Int, 2n, n),
        storephase,
        false,
        inversemod,
        zeros(Int, 2n, n),
        zeros(Int, nrows),
        zeros(Int, 2n),
        zeros(Int, n),
        zeros(Int, 2n),
        zeros(Int, n),
        zeros(Int, n),
        zeros(Int, n),
    )

    if preset_state === nothing
        # Before the rebuild, not after: an invalid generator set would
        # otherwise produce a dual basis that cannot satisfy duality, and the
        # failure would surface somewhere far from its cause.
        check && _validate_generators!(tab)
        rebuild_destabilizers!(tab)
        _recompute_xdotz_cache!(tab)
    else
        _preset_destabilizers!(tab, preset_state, preset_basis)
    end

    return tab
end

#############################
# Destabilizer construction #
#############################

@inline function _pivot_columns!(
    A::AbstractMatrix{Int},
    m::Int,
    ncols::Int,
    d::Int,
    inversemod::InverseMod,
    pivots::Vector{Int},
)
    r = 1
    c = 1
    pivcount = 0
    while r <= m && c <= ncols
        pivot = r
        while pivot <= m && A[pivot, c] == 0
            pivot += 1
        end
        if pivot > m
            c += 1
            continue
        end

        if pivot != r
            @turbo for j in 1:ncols
                t = A[r, j]
                A[r, j] = A[pivot, j]
                A[pivot, j] = t
            end
        end

        # Row-strided rather than column-strided, but the contract is the same:
        # `rebuild_destabilizers!` fills `A` through `mod(..., d)`, so every
        # entry is reduced into [0, d) before this runs.
        α = inversemod(A[r, c], d)
        scale_mod!(view(A, r, c:ncols), α, d)

        for rr in (r+1):m
            β = A[rr, c]
            β == 0 && continue
            # rr >= r+1, so these are disjoint rows.
            submul_mod!(view(A, rr, c:ncols), view(A, r, c:ncols), β, d)
        end

        pivcount += 1
        pivots[pivcount] = c
        r += 1
        c += 1
    end
    return pivcount
end

function _inv_matrix_mod!(
    invA::AbstractMatrix{Int},
    Awork::AbstractMatrix{Int},
    m::Int,
    d::Int,
    inversemod::InverseMod,
)
    (size(Awork, 1) >= m && size(Awork, 2) >= m) || throw(ArgumentError("Matrix workspace too small."))
    (size(invA, 1) >= m && size(invA, 2) >= m) || throw(ArgumentError("Inverse workspace too small."))

    fill!(invA, 0)
    @inbounds for i in 1:m
        invA[i, i] = 1
    end

    for c in 1:m
        pivot = c
        while pivot <= m && Awork[pivot, c] == 0
            pivot += 1
        end
        pivot > m && throw(ArgumentError("Matrix is singular modulo d."))

        if pivot != c
            @turbo for j in 1:m
                t = Awork[c, j]
                Awork[c, j] = Awork[pivot, j]
                Awork[pivot, j] = t

                t2 = invA[c, j]
                invA[c, j] = invA[pivot, j]
                invA[pivot, j] = t2
            end
        end

        # Two matrices, so this is two passes where it used to be one fused
        # loop. Both start reduced -- `Awork` is copied from the `mod`-reduced
        # `A`, `invA` from the identity -- and at d = 2 every α is 1, which
        # `scale_mod!` skips outright.
        α = inversemod(Awork[c, c], d)
        scale_mod!(view(Awork, c, 1:m), α, d)
        scale_mod!(view(invA, c, 1:m), α, d)

        for rr in 1:m
            rr == c && continue
            β = Awork[rr, c]
            β == 0 && continue
            # rr != c (guarded above), so these are disjoint rows.
            submul_mod!(view(Awork, rr, 1:m), view(Awork, c, 1:m), β, d)
            submul_mod!(view(invA, rr, 1:m), view(invA, c, 1:m), β, d)
        end
    end

    return invA
end

function rebuild_destabilizers!(tab::DestabilizerTableau)
    n = tab.n
    m = tab.m
    d = tab.d
    stab = tab.stab
    destab = tab.destab

    fill!(destab, 0)
    m == 0 && return destab

    # These five are scratch for this call and nothing else. They used to be
    # tableau fields, which cost 6n^2 + n Ints on EVERY DestabilizerTableau --
    # about half its footprint -- to serve a function that runs at most once
    # per tableau, on the raw-matrix path alone. Presets reach
    # `_preset_destabilizers!` and never come here at all, so they were paying
    # for scratch they could not use. Locals cost one allocation on a path that
    # is already O(n^3).
    #
    # `zeros` rather than `undef`: rows m+1:n of A and Awork are never written
    # here, and this keeps them defined, as the preallocated fields did.

    # Build A = Sᵀ J (size m × 2n)
    A = zeros(Int, n, 2n)
    @inbounds for k in 1:m
        for q in 1:n
            A[k, q] = mod(stab[n+q, k], d)
            A[k, n+q] = mod(-stab[q, k], d)
        end
    end

    Awork = zeros(Int, n, 2n)
    @turbo for j in 1:(2n), i in 1:m
        Awork[i, j] = A[i, j]
    end

    pivots = zeros(Int, n)
    pivcount = _pivot_columns!(Awork, m, 2n, d, tab.inversemod, pivots)
    # If generators are not independent, destabilizers are undefined; leave destab zeroed.
    pivcount == m || return destab

    A_P = zeros(Int, n, n)
    @inbounds for j in 1:m
        pj = pivots[j]
        @turbo for i in 1:m
            A_P[i, j] = A[i, pj]
        end
    end

    @turbo for j in 1:m, i in 1:m
        Awork[i, j] = A_P[i, j]
    end

    A_inv = zeros(Int, n, n)
    _inv_matrix_mod!(A_inv, Awork, m, d, tab.inversemod)

    @inbounds for i in 1:m
        p = pivots[i]
        @turbo for j in 1:m
            destab[p, j] = mod(A_inv[i, j], d)
        end
    end
    return destab
end

"""
Fill `tab.destab` and `tab.xdotz_cache` with the closed-form duals of a preset
state, in place of the generic O(n^3) `rebuild_destabilizers!`.

Preset stabilizers are supported on a single qudit each (`:product`) or form a
chain (`:ghz`), so their duals can be written down:

  product, column j:   `:Z` -> `X_j`,  `:X` -> `Z_j^(d-1)`,  `:Y` -> `X_j`
  ghz:                 `D_1 = Z_1^(d-1)`,  `D_j = X_1...X_{j-1}` for `j >= 2`

Each satisfies the duality relation `<D_j, S_k> = delta_jk` directly. `:mixed`
has no active generators, so its dual block stays zero.
"""
function _preset_destabilizers!(tab::DestabilizerTableau, state::Symbol, basis_spec)
    n = tab.n
    d = tab.d
    destab = tab.destab
    cache = tab.xdotz_cache

    fill!(destab, 0)
    fill!(cache, 0)

    if state === :mixed
        return nothing
    elseif state === :ghz
        n == 0 && return nothing
        destab[n+1, 1] = d - 1              # D_1 = Z_1^(d-1)
        @inbounds for j in 2:n, q in 1:(j-1)
            destab[q, j] = 1                # D_j = X_1 ... X_{j-1}
        end
        return nothing                      # every GHZ generator has x.z = 0
    elseif state === :product
        @inbounds for j in 1:n
            b = _preset_basis_at(basis_spec, j)
            if b === :X
                destab[n+j, j] = d - 1      # D_j = Z_j^(d-1)
            else
                destab[j, j] = 1            # :Z and :Y both take D_j = X_j
                b === :Y && (cache[j] = 1)  # x.z = 1 only in the Y basis
            end
        end
        return nothing
    end

    throw(ArgumentError("Unknown preset state: $state."))
end

@inline _preset_basis_at(basis::Symbol, ::Int) = _canonical_basis_symbol(basis)
@inline _preset_basis_at(basis::AbstractVector{<:Symbol}, j::Int) =
    _canonical_basis_symbol(basis[j])
@inline _preset_basis_at(basis::Tuple, j::Int) = _canonical_basis_symbol(basis[j])

#############################
# Cache maintenance helpers #
#############################

@inline function _recompute_xdotz_cache!(tab::DestabilizerTableau)
    n = tab.n
    m = tab.m
    d = tab.d
    xdotz_cache = tab.xdotz_cache
    stab = tab.stab
    @inbounds for j in 1:m
        xdotz_cache[j] = dot_xz_col(stab, n, j, d)
    end
    @inbounds for j in (m+1):n
        xdotz_cache[j] = 0
    end
    return nothing
end

@inline function _update_xdotz_cache!(tab::DestabilizerTableau, col::Int)
    tab.xdotz_cache[col] = dot_xz_col(tab.stab, tab.n, col, tab.d)
    return nothing
end

#############################
# Symplectic helpers        #
#############################

@inline function _symplectic_col_col(A::AbstractMatrix{<:Integer}, colA::Int, B::AbstractMatrix{<:Integer}, colB::Int, n::Int)
    s = 0
    @turbo for q in 1:n
        s += A[q, colA] * B[n+q, colB]
    end
    @turbo for q in 1:n
        s -= A[n+q, colA] * B[q, colB]
    end
    return s
end

"""
Collect into `supp` the qudit indices where column `col` of `A` is nonzero in
either its X or its Z half, returning how many were found.

Every term of a symplectic pairing against that column carries a factor from
one of those two halves, so all terms outside this index set vanish and a
pairing restricted to `supp[1:nsupp]` equals the full `2n`-term sum exactly.
"""
@inline function _column_support!(supp::Vector{Int}, A::AbstractMatrix{<:Integer}, col::Int, n::Int)
    nsupp = 0
    # Loop-carried counter, so neither @turbo nor @simd applies here.
    @inbounds for q in 1:n
        if A[q, col] != 0 || A[n+q, col] != 0
            nsupp += 1
            supp[nsupp] = q
        end
    end
    return nsupp
end

"""
`_symplectic_col_col` restricted to the qudit indices in `supp[1:nsupp]`.
Equal to the full pairing whenever `supp` covers the support of column `colB`
of `B` (see `_column_support!`), at `O(nsupp)` instead of `O(n)`.
"""
@inline function _symplectic_col_col_support(
    A::AbstractMatrix{<:Integer}, colA::Int,
    B::AbstractMatrix{<:Integer}, colB::Int,
    n::Int, supp::Vector{Int}, nsupp::Int,
)
    s = 0
    @inbounds @simd for k in 1:nsupp
        q = supp[k]
        s += A[q, colA] * B[n+q, colB] - A[n+q, colA] * B[q, colB]
    end
    return s
end

@inline function _symplectic_vec_col(vec::AbstractVector{<:Integer}, B::AbstractMatrix{<:Integer}, colB::Int, n::Int)
    s = 0
    @turbo for q in 1:n
        s += vec[q] * B[n+q, colB]
    end
    @turbo for q in 1:n
        s -= vec[n+q] * B[q, colB]
    end
    return s
end

#############################
# Destabilizer-specific API #
#############################

function reset!(tab::DestabilizerTableau; state::Symbol=:mixed, basis=:Z)
    state_norm, basis_spec = _normalize_state_and_basis(state, basis, tab.n)
    m = _preset_tableau!(tab.stab, tab.d, tab.n, state_norm, basis_spec, tab.storephase)
    tab.m = m
    tab.iscanonical = false
    _preset_destabilizers!(tab, state_norm, basis_spec)
    return tab
end

function reset!(tab::DestabilizerTableau, state::Symbol; basis=:Z)
    return reset!(tab; state=state, basis=basis)
end

# give the struct a nice standard presentation (stabilizers + destabilizers)
function Base.show(io::IO, tab::DestabilizerTableau)
    println(io, "Destabilizer Tableau:")
    println(io, "    Qudit dimension:  d = ", tab.d)
    println(io, "    Number of Qudits: n = ", tab.n)
    println(io, "    Generators:       m = ", tab.m)

    tab.n >= max_qudits_display[] && (println(io, "    Tableau is too large to display."); return)

    if tab.m < tab.n
        println(io, "    Mixed tableau (m < n generators):")
    else
        println(io, "    Tableau:")
    end

    if tab.m == 0
        println(io, "    (no generators; maximally mixed on the full space)")
        return
    end

    tabview = view(tab.stab, :, 1:tab.m)
    destview = view(tab.destab, 1:(2*tab.n), 1:tab.m)
    maxstab = maximum(abs, tabview)
    maxdest = maximum(abs, destview)
    N = ndigits(max(maxstab, maxdest)) - 1
    extraspace = 0
    isodd(N) && isodd(tab.n) && (extraspace += 1)
    dash_len = max(0, tab.n * (N + 2) ÷ 2 - 2 + extraspace)

    header = if tab.n > 1
        left = "-"^dash_len * " X " * "-"^dash_len
        sep = extraspace == 1 ? "  " : "   "
        right = "-"^dash_len * " Z " * "-"^dash_len
        left * sep * right
    else
        left = "-"^dash_len * "X " * "-"^dash_len
        right = "-"^dash_len * " Z " * "-"^dash_len
        left * " " * right
    end

    # Stabilizers
    println(io, "     Stabilizers:")
    println(io, "     ", header)
    for col in 1:tab.m
        print(io, "    ")
        for row in 1:size(tab.stab, 1)
            ((row == tab.n + 1) || (row == 2 * tab.n + 1)) && print(io, " |")
            print(io, lpad(tab.stab[row, col], N + 2))
        end
        println(io)
    end

    # Separator + Destabilizers
    println(io, "     ", "-"^length(header))
    println(io, "     Destabilizers:")
    println(io, "     ", header)
    for col in 1:tab.m
        print(io, "    ")
        for row in 1:(2*tab.n)
            (row == tab.n + 1) && print(io, " |")
            print(io, lpad(tab.destab[row, col], N + 2))
        end
        println(io)
    end
end
