"""
    StabilizerTableau(d::Int, n::Int; state::Symbol=:mixed, basis=:Z, storephase::Bool=true)
    StabilizerTableau(d::Int, n::Int, state::Symbol; kwargs...)
    StabilizerTableau(d::Int, tableau::AbstractMatrix{<:Integer}; m::Union{Int,Nothing}=nothing, storephase::Union{Bool,Nothing}=nothing)

Construct a stabilizer tableau for an `n`-qudit *stabilizer density operator* (mixed-state stabilizer formalism).

# Arguments
- `d::Int`: Qudit dimension (must be a prime number).
- `n::Int`: Number of qudits (only for the `d, n` constructor).
- `state::Symbol`: Preset state for the positional `state` constructor.
- `tableau::AbstractMatrix{<:Integer}`: An integer matrix in either `(2n + storephase) × m` or `m × (2n + storephase)` layout.

# Keyword Arguments
- `state::Symbol=:mixed`: Preset state (`:mixed`, `:product`, `:ghz`). Aliases `:X/:Y/:Z` map to `:product` in that basis.
- `basis=:Z`: Basis for product states (`:X`, `:Y`, `:Z`, or a per-qudit vector/tuple of Symbols).
- `storephase::Bool=true`: Whether to store the phase row (for the `(d, n)` constructor). When
  constructing from a `tableau`, `storephase` is inferred from the matrix shape if not provided.
- `m::Union{Int,Nothing}=nothing`: Number of active generator columns (for the `(d, tableau)` constructor).
- `inversemod::InverseMod=PrecomputedInvMod(d)`: Inversion strategy used for phase calculations.

# Examples
```julia
tab = StabilizerTableau(2, 3; state=:mixed)
tab = StabilizerTableau(2, 3; state=:product, basis=:X)

raw = reshape(Int[0, 1, 0], 3, 1)
tab = StabilizerTableau(2, raw)
```

# Notes
## Representation
We store an abelian stabilizer subgroup `S` generated by `m` independent commuting Paulis (`0 ≤ m ≤ n`).

The internal tableau has shape `(2n + storephase) × n`.
- Only the **first `m` columns** are active generator columns.
- Columns `m+1:n` are unused (kept zero) and can be used as capacity when measurements increase `m`.

## Phase convention
If `storephase=true`, the last row stores the phase exponent `k`:
- odd prime `d`:  ω^k with k mod d
- d=2:            i^k with k mod 4

## Preset states
- `:mixed` (maximally mixed; `m=0`)
- `:product` (pure product state; `basis` is `:X`, `:Y`, `:Z`, or a vector/tuple of length `n`)
- `:ghz` (generalized GHZ on `n` qudits)

See also [`reset!`](@ref).
"""
mutable struct StabilizerTableau{T<:InverseMod} <: AbstractTableau
    d::Int                             # qudit dimension
    n::Int                             # number of qudits
    m::Int                             # number of active generator columns (0 ≤ m ≤ n)
    stab::Matrix{Int}                 # tableau has dimensions (2n + storephase) × n
    storephase::Bool                   # whether phase information is stored
    iscanonical::Bool                  # true if the tableau is in canonical (RCEF) form
    inversemod::T                      # inverse mod function for dimension d

    # workspaces
    workspace::Matrix{Int}             # 2n×n (used by entanglement_entropy)
    generator_workspace::Vector{Int}   # length 2n + storephase

    # workspace for canonicalize!
    pivcol_of_row::Vector{Int}         # length 2n (pivot column for each row if canonical)
    xdotz_cache::Vector{Int}           # length n (stores x·z values for each generator)

    # workspace for expectation value calculations
    res_workspace::Vector{Int}         # length 2n
    c_workspace::Vector{Int}           # length n
    zacc_workspace::Vector{Int}        # length n
end

function StabilizerTableau(d::Int, n::Int;
    state::Symbol=:mixed,
    basis=:Z,
    storephase::Bool=true,
    inversemod::T=PrecomputedInvMod(d)
) where {T<:InverseMod}
    state_norm, basis_spec = _normalize_state_and_basis(state, basis, n)
    tab, m = _preset_tableau(d, n, state_norm, basis_spec, storephase)
    return _build_stabilizer_tableau(d, n, m, tab, storephase, inversemod)
end

StabilizerTableau(d::Int, n::Int, state::Symbol; kwargs...) = StabilizerTableau(d, n; state=state, kwargs...)

function StabilizerTableau(d::Int, tableau::AbstractMatrix{<:Integer};
    m::Union{Int,Nothing}=nothing,
    storephase::Union{Bool,Nothing}=nothing,
    inversemod::T=PrecomputedInvMod(d)
) where {T<:InverseMod}
    m !== nothing && m < 0 && throw(ArgumentError("m must satisfy 0 ≤ m ≤ n."))
    tab_in = (tableau isa Matrix{Int}) ? tableau : Matrix{Int}(tableau)
    layout = _infer_tableau_layout(size(tab_in, 1), size(tab_in, 2), m, storephase)
    layout === nothing && throw(ArgumentError(
        "Tableau must have shape (2n + storephase) × m or m × (2n + storephase) with m ≤ n."
    ))

    if layout.transpose
        tab_in = permutedims(tab_in)
    end

    return _build_stabilizer_tableau(d, layout.n, layout.m, tab_in, layout.storephase, inversemod)
end

function _build_stabilizer_tableau(
    d::Int,
    n::Int,
    m::Int,
    tableau_in::AbstractMatrix{<:Integer},
    storephase::Bool,
    inversemod::T,
) where {T<:InverseMod}
    !Primes.isprime(d) && throw(ArgumentError("Qudit dimension d must be a prime number."))
    (0 ≤ m ≤ n) || throw(ArgumentError("m must satisfy 0 ≤ m ≤ n."))

    nrows = 2n + (storephase ? 1 : 0)
    size(tableau_in, 1) == nrows || throw(ArgumentError("Tableau row count must be 2n (+1 if storephase=true)."))

    # We keep capacity n columns, but accept either n columns or m columns and pad.
    tab_in = (tableau_in isa Matrix{Int}) ? tableau_in : Matrix{Int}(tableau_in)
    tab = if size(tab_in, 2) == n
        tab_in
    elseif size(tab_in, 2) == m
        tmp = zeros(Int, nrows, n)
        tmp[:, 1:m] .= tab_in
        tmp
    else
        throw(ArgumentError("Tableau must have either n columns (capacity) or m columns (active generators)."))
    end

    # Reduce entries mod d / mod phase modulus
    @turbo for j in 1:n
        for i in 1:(2n)
            tab[i, j] = mod(tab[i, j], d)
        end
    end
    if storephase
        d_phase = phase_modulus(d)
        prow = 2n + 1
        @turbo for j in 1:n
            tab[prow, j] = mod(tab[prow, j], d_phase)
        end
    end

    # Ensure unused columns are zeroed.
    if m < n
        @turbo for j in (m+1):n, i in axes(tab, 1)
            tab[i, j] = 0
        end
    end

    return StabilizerTableau{T}(
        d,
        n,
        m,
        tab,
        storephase,
        false,
        inversemod,
        zeros(Int, 2n, n),
        zeros(Int, nrows),
        zeros(Int, 2n),
        zeros(Int, n),
        zeros(Int, 2n),
        zeros(Int, n),
        zeros(Int, n),
    )
end

@inline function _layout_from_dims(dim_nrows::Int, dim_cols::Int, m::Union{Int,Nothing}, storephase::Union{Bool,Nothing})
    storephase_dim = isodd(dim_nrows)
    n = storephase_dim ? (dim_nrows - 1) ÷ 2 : dim_nrows ÷ 2

    if storephase !== nothing && storephase != storephase_dim
        return nothing
    end

    if m === nothing
        if dim_cols == n
            return (n=n, m=n, storephase=storephase_dim)
        elseif dim_cols < n
            return (n=n, m=dim_cols, storephase=storephase_dim)
        else
            return nothing
        end
    else
        (0 ≤ m ≤ n) || return nothing
        if dim_cols == n || dim_cols == m
            return (n=n, m=m, storephase=storephase_dim)
        end
    end
    return nothing
end

@inline function _infer_tableau_layout(rows::Int, cols::Int, m::Union{Int,Nothing}, storephase::Union{Bool,Nothing})
    cand = _layout_from_dims(rows, cols, m, storephase)
    cand !== nothing && return (transpose=false, n=cand.n, m=cand.m, storephase=cand.storephase)

    cand = _layout_from_dims(cols, rows, m, storephase)
    cand !== nothing && return (transpose=true, n=cand.n, m=cand.m, storephase=cand.storephase)

    return nothing
end

"""
    reset!(tab::StabilizerTableau; state::Symbol=:mixed, basis=:Z)
    reset!(tab::StabilizerTableau, state::Symbol; basis=:Z)

Reset an existing stabilizer tableau in-place to a preset state.

# Arguments
- `tab::StabilizerTableau`: The tableau to reset.

# Keyword Arguments
- `state::Symbol=:mixed`: Preset state (`:mixed`, `:product`, `:ghz`). Aliases `:X/:Y/:Z` map to `:product` in that basis.
- `basis=:Z`: Basis for product states (`:X`, `:Y`, `:Z`, or a per-qudit vector/tuple of Symbols).

# Examples
```julia
tab = StabilizerTableau(2, 3; state=:mixed)
reset!(tab; state=:product, basis=:Z)
reset!(tab, :ghz)
```

# Notes
Uses the existing `n` and `storephase` of `tab`. See [`StabilizerTableau`](@ref).
"""
function reset!(tab::StabilizerTableau; state::Symbol=:mixed, basis=:Z)
    state_norm, basis_spec = _normalize_state_and_basis(state, basis, tab.n)
    m = _preset_tableau!(tab.stab, tab.d, tab.n, state_norm, basis_spec, tab.storephase)
    tab.m = m
    tab.iscanonical = false
    return tab
end

function reset!(tab::StabilizerTableau, state::Symbol; basis=:Z)
    return reset!(tab; state=state, basis=basis)
end

@inline function _canonical_basis_symbol(basis::Symbol)::Symbol
    if basis === :X || basis === :x
        return :X
    elseif basis === :Y || basis === :y
        return :Y
    elseif basis === :Z || basis === :z
        return :Z
    end
    throw(ArgumentError("Unknown basis symbol: $basis. Use :X, :Y, or :Z."))
end

@inline function _basis_is_default(basis)::Bool
    if basis === :Z
        return true
    elseif basis isa Symbol
        return _canonical_basis_symbol(basis) === :Z
    end
    return false
end

@inline function _normalize_state_and_basis(state::Symbol, basis, n::Int)
    if state === :X || state === :x || state === :Y || state === :y || state === :Z || state === :z
        basis_sym = _canonical_basis_symbol(state)
        if basis isa Symbol
            basis_can = _canonical_basis_symbol(basis)
            if !(basis_can === :Z || basis_can === basis_sym)
                throw(ArgumentError("state=$state implies basis=$basis_sym; omit basis or set it to $basis_sym."))
            end
        elseif basis !== :Z
            throw(ArgumentError("state=$state implies basis=$basis_sym; omit basis or set it to $basis_sym."))
        end
        return :product, basis_sym
    end

    if state === :mixed || state === :maxmixed || state === :maximally_mixed || state === :totally_mixed
        if !_basis_is_default(basis)
            throw(ArgumentError("basis is only used for state=:product."))
        end
        return :mixed, nothing
    elseif state === :product || state === :prod || state === :product_state
        return :product, basis
    elseif state === :ghz
        if !_basis_is_default(basis)
            throw(ArgumentError("basis is only used for state=:product."))
        end
        return :ghz, nothing
    end

    throw(ArgumentError("Unknown state: $state. Use :mixed, :product, or :ghz."))
end

function _preset_tableau(d::Int, n::Int, state::Symbol, basis_spec, storephase::Bool)
    nrows = 2n + (storephase ? 1 : 0)
    tab = zeros(Int, nrows, n)

    m = _preset_tableau!(tab, d, n, state, basis_spec, storephase)
    return tab, m
end

function _preset_tableau!(tab::Matrix{Int}, d::Int, n::Int, state::Symbol, basis_spec, storephase::Bool)
    fill!(tab, 0)

    if state === :mixed
        return 0
    elseif state === :product
        _fill_product_state!(tab, d, n, basis_spec, storephase)
        _reduce_tableau_mod!(tab, d, n, storephase)
        return n
    elseif state === :ghz
        _fill_ghz_state!(tab, d, n)
        _reduce_tableau_mod!(tab, d, n, storephase)
        return n
    end

    throw(ArgumentError("Unknown preset state: $state."))
end

function _reduce_tableau_mod!(tab::Matrix{Int}, d::Int, n::Int, storephase::Bool)
    @turbo for j in 1:n
        for i in 1:(2n)
            tab[i, j] = mod(tab[i, j], d)
        end
    end
    if storephase
        d_phase = phase_modulus(d)
        prow = 2n + 1
        @turbo for j in 1:n
            tab[prow, j] = mod(tab[prow, j], d_phase)
        end
    end
    return nothing
end

@inline function _set_product_column!(tab::Matrix{Int}, d::Int, n::Int, col::Int, basis::Symbol, storephase::Bool)
    if basis === :X
        tab[col, col] = 1
    elseif basis === :Z
        tab[n + col, col] = 1
    else
        @assert basis === :Y
        tab[col, col] = 1
        tab[n + col, col] = 1
        if storephase && d == 2
            tab[2n + 1, col] = 1
        end
    end
    return nothing
end

function _fill_product_state!(tab::Matrix{Int}, d::Int, n::Int, basis::Symbol, storephase::Bool)
    b = _canonical_basis_symbol(basis)

    @inbounds for j in 1:n
        _set_product_column!(tab, d, n, j, b, storephase)
    end
    return nothing
end

function _fill_product_state!(tab::Matrix{Int}, d::Int, n::Int, basis_vec::AbstractVector{<:Symbol}, storephase::Bool)
    length(basis_vec) == n || throw(ArgumentError("basis must have length n=$n."))

    @inbounds for j in 1:n
        b = _canonical_basis_symbol(basis_vec[j])
        _set_product_column!(tab, d, n, j, b, storephase)
    end
    return nothing
end

function _fill_product_state!(tab::Matrix{Int}, d::Int, n::Int, basis_tuple::Tuple, storephase::Bool)
    length(basis_tuple) == n || throw(ArgumentError("basis must have length n=$n."))

    @inbounds for j in 1:n
        b = basis_tuple[j]
        b isa Symbol || throw(ArgumentError("basis tuple entries must be Symbols."))
        b = _canonical_basis_symbol(b)
        _set_product_column!(tab, d, n, j, b, storephase)
    end
    return nothing
end

function _fill_product_state!(tab::Matrix{Int}, d::Int, n::Int, basis, storephase::Bool)
    throw(ArgumentError("basis must be a Symbol or a vector/tuple of Symbols."))
end

function _fill_ghz_state!(tab::Matrix{Int}, _d::Int, n::Int)
    n == 0 && return nothing

    # Generator 1: X1 X2 ... Xn
    @inbounds for q in 1:n
        tab[q, 1] = 1
    end

    # Generators 2..n: Z_{i-1} Z_i^{-1}
    @inbounds for col in 2:n
        i = col
        tab[n + (i - 1), col] = 1
        tab[n + i, col] = -1
    end
    return nothing
end

"""Number of active generator columns."""
@inline ngens(tab::StabilizerTableau) = tab.m

"""True iff the represented stabilizer density operator is mixed (i.e. m < n)."""
@inline is_mixed(tab::StabilizerTableau) = tab.m < tab.n

const max_qudits_display = Ref(30)  # maximum number of qudits to display the full tableau

# give the struct a nice standard presentation
function Base.show(io::IO, tab::StabilizerTableau)
    println(io, "Stabilizer Tableau:")
    println(io, "    Qudit dimension:  d = ", tab.d)
    println(io, "    Number of Qudits: n = ", tab.n)
    println(io, "    Generators:       m = ", tab.m)
    println(io, "    Canonical form:   ", tab.iscanonical)
    # println(io, "    Mixed state:      ", is_mixed(tab))

    tab.n >= max_qudits_display[] && (println(io, "    Tableau is too large to display."); return)

    if is_mixed(tab)
        println(io, "    Mixed tableau (m < n generators):")
    else
        println(io, "    Tableau:")
    end

    if tab.m == 0
        println(io, "     (no generators; maximally mixed on the full space)")
        return
    end

    tabview = view(tab.stab, :, 1:tab.m)
    N = ndigits(maximum(abs, tabview)) - 1
    extraspace = 0
    isodd(N) && isodd(tab.n) && (extraspace += 1)
    dash_len = max(0, tab.n * (N + 2) ÷ 2 - 2 + extraspace)
    print(io, "     ")
    if tab.n > 1
        print(io, "-"^dash_len, " X ", "-"^dash_len)
        print(io, extraspace == 1 ? "  " : "   ")
    else
        print(io, "-"^dash_len, "X ", "-"^dash_len)
        print(io, " ")
    end
    print(io, "-"^dash_len, " Z ", "-"^dash_len)
    println(io)

    for col in 1:tab.m
        print(io, "    ")
        for row in 1:size(tab.stab, 1)
            ((row == tab.n + 1) || (row == 2 * tab.n + 1)) && print(io, " |")
            print(io, lpad(tab.stab[row, col], N + 2))
        end
        println(io)
    end
end
