"""
    StabilizerTableau(d::Int, n::Int, m::Int, tableau::AbstractMatrix{<:Integer}, storephase::Bool)
    StabilizerTableau(d::Int, n::Int, tableau::AbstractMatrix{<:Integer}; m::Int=n, storephase::Bool=size(tableau,1)==2n+1)
    StabilizerTableau(d::Int, tableau::AbstractMatrix{<:Integer})

A stabilizer tableau for an `n`-qudit *stabilizer density operator* (mixed-state stabilizer formalism).

Representation
-------------
We store an abelian stabilizer subgroup `S` generated by `m` independent commuting Paulis (with `0 ≤ m ≤ n`).

The tableau has shape `(2n + storephase) × n`.

* Only the **first `m` columns** are active generator columns.
* Columns `m+1:n` are unused (kept zero) and can be used as capacity when measurements increase `m`.

Phase convention
---------------
If `storephase=true`, the last row stores the phase exponent `k`:

* odd prime `d`:  ω^k with k mod d
* d=2:           i^k with k mod 4
"""
mutable struct StabilizerTableau{T<:InverseMod}
    d::Int                             # qudit dimension
    n::Int                             # number of qudits
    m::Int                             # number of active generator columns (0 ≤ m ≤ n)
    tableau::Matrix{Int}               # tableau has dimensions (2n + storephase) × n
    storephase::Bool                   # whether phase information is stored
    iscanonical::Bool                  # true if the tableau is in canonical (RCEF) form
    inversemod::T                      # inverse mod function for dimension d

    # workspaces
    workspace::Matrix{Int}             # 2n×n (used by entanglement_entropy)
    generator_workspace::Vector{Int}   # length 2n + storephase

    # workspace for canonicalize!
    pivcol_of_row::Vector{Int}         # length 2n (pivot column for each row if canonical)
    xdotz_cache::Vector{Int}           # length n (stores x·z values for each generator)

    # workspace for expectation value calculations
    res_workspace::Vector{Int}         # length 2n
    c_workspace::Vector{Int}           # length n
    zacc_workspace::Vector{Int}        # length n

    function StabilizerTableau(
        d::Int,
        n::Int,
        m::Int,
        tableau_in::AbstractMatrix{<:Integer},
        storephase::Bool,
        inversemod::T,
    ) where {T<:InverseMod}

        !Primes.isprime(d) && throw(ArgumentError("Qudit dimension d must be a prime number."))
        (0 ≤ m ≤ n) || throw(ArgumentError("m must satisfy 0 ≤ m ≤ n."))

        nrows = 2n + (storephase ? 1 : 0)
        size(tableau_in, 1) == nrows || throw(ArgumentError("Tableau row count must be 2n (+1 if storephase=true)."))

        # We keep capacity n columns, but accept either n columns or m columns and pad.
        tab_in = (tableau_in isa Matrix{Int}) ? tableau_in : Matrix{Int}(tableau_in)
        tab = if size(tab_in, 2) == n
            tab_in
        elseif size(tab_in, 2) == m
            tmp = zeros(Int, nrows, n)
            tmp[:, 1:m] .= tab_in
            tmp
        else
            throw(ArgumentError("Tableau must have either n columns (capacity) or m columns (active generators)."))
        end

        # Reduce entries mod d / mod phase modulus
        @turbo for j in 1:n
            for i in 1:(2n)
                tab[i, j] = mod(tab[i, j], d)
            end
        end
        if storephase
            d_phase = phase_modulus(d)
            prow = 2n + 1
            @turbo for j in 1:n
                tab[prow, j] = mod(tab[prow, j], d_phase)
            end
        end

        # Ensure unused columns are zeroed.
        if m < n
            @turbo for j in (m+1):n, i in axes(tab, 1)
                tab[i, j] = 0
            end
        end

        new{T}(
            d,
            n,
            m,
            tab,
            storephase,
            false,
            inversemod,
            zeros(Int, 2n, n),
            zeros(Int, nrows),
            zeros(Int, 2n),
            zeros(Int, n),
            zeros(Int, 2n),
            zeros(Int, n),
            zeros(Int, n),
        )
    end

    function StabilizerTableau(
        d::Int,
        n::Int,
        tableau::AbstractMatrix{<:Integer};
        m::Int=n,
        storephase::Bool=(size(tableau, 1) == 2n + 1),
        inversemod::T=PrecomputedInvMod(d),
    ) where {T<:InverseMod}
        return StabilizerTableau(d, n, m, tableau, storephase, inversemod)
    end

    function StabilizerTableau(d::Int, tableau::AbstractMatrix{<:Integer})
        # Interpret as a "full capacity" tableau: n = number of columns, m defaults to n.
        n = size(tableau, 1) ÷ 2
        m = size(tableau, 2)
        return StabilizerTableau(d, n, tableau; m=m)
    end

    function StabilizerTableau(d::Int, n::Int;
        storephase::Bool=true,
        inversemod::T=PrecomputedInvMod(d)
    ) where {T<:InverseMod}
        # create maximally mixed stabilizer tableau on n qudits
        nrows = 2n + (storephase ? 1 : 0)
        tab = zeros(Int, nrows, n)
        return StabilizerTableau(d, n, 0, tab, storephase, inversemod)
    end

end

"""Number of active generator columns."""
@inline ngens(stabtab::StabilizerTableau) = stabtab.m

"""True iff the represented stabilizer density operator is mixed (i.e. m < n)."""
@inline is_mixed(stabtab::StabilizerTableau) = stabtab.m < stabtab.n

const max_qudits_display = Ref(30)  # maximum number of qudits to display the full tableau

# give the struct a nice standard presentation
function Base.show(io::IO, stabtab::StabilizerTableau)
    println(io, "Stabilizer Tableau:")
    println(io, "    Qudit dimension:  d = ", stabtab.d)
    println(io, "    Number of Qudits: n = ", stabtab.n)
    println(io, "    Generators:       m = ", stabtab.m)
    println(io, "    Canonical form:   ", stabtab.iscanonical)
    # println(io, "    Mixed state:      ", is_mixed(stabtab))

    stabtab.n >= max_qudits_display[] && (println(io, "    Tableau is too large to display."); return)

    if is_mixed(stabtab)
        println(io, "    Mixed tableau (m < n generators):")
    else
        println(io, "    Tableau:")
    end

    if stabtab.m == 0
        println(io, "    (no generators; maximally mixed on the full space)")
        return
    end

    tabview = view(stabtab.tableau, :, 1:stabtab.m)
    N = ndigits(maximum(abs, tabview)) - 1
    extraspace = 0
    isodd(N) && isodd(stabtab.n) && (extraspace += 1)
    dash_len = max(0, stabtab.n * (N + 2) ÷ 2 - 2 + extraspace)
    print(io, "    ")
    if stabtab.n > 1
        print(io, "-"^dash_len, " X ", "-"^dash_len)
        print(io, extraspace == 1 ? "  " : "   ")
    else
        print(io, "-"^dash_len, "X ", "-"^dash_len)
        print(io, " ")
    end
    print(io, "-"^dash_len, " Z ", "-"^dash_len)
    println(io)

    for col in 1:stabtab.m
        print(io, "   ")
        for row in 1:size(stabtab.tableau, 1)
            ((row == stabtab.n + 1) || (row == 2 * stabtab.n + 1)) && print(io, " |")
            print(io, lpad(stabtab.tableau[row, col], N + 2))
        end
        println(io)
    end
end
