##### Exact expansion of stabilizer states (private) #####
#
# Walks a stabilizer group and locates the support of a pure state, for the
# dense conversions in `dense_states.jl`. Nothing here is exported and nothing
# here writes to a tableau: callers pass either a matrix they own or read-only
# access to `tab.stab`, plus scratch vectors they allocated themselves.
#
# Conventions (docs/src/conventions.md). A column (x, z, a) denotes
#
#     P(x, z, a) = ζ^a ⊗_q X_q^(x_q) Z_q^(z_q),   ζ = i (d = 2) or ω (odd d),
#
# with p = phase_modulus(d) and s = p ÷ d, so that ω = ζ^s. The product rule is
#
#     P(x, z, a) · P(x', z', a') = P(x + x', z + z', a + a' + s (z · x')),
#
# the same `z_left · x_right` cross term `_canonicalize_tableau!` adds when it
# forms `g_jj <- g_jj * (g_c)^texp`.
#
# Arithmetic stays inside the package envelope: every caller has checked
# `d <= max_safe_dimension(n)`, so the unreduced dot products below, at most
# n (d-1)^2, fit in an `Int`.

# `d^e` when it does not exceed `limit`, else -1. The running value never passes
# `limit`, so this cannot overflow however large `e` is: `r <= limit ÷ d` implies
# `r * d <= limit`, and `r > limit ÷ d` implies `r * d > limit`.
# Requires `d >= 2`, `e >= 0`, `limit >= 1`.
@inline function _bounded_pow(d::Int, e::Int, limit::Int)
    r = 1
    for _ in 1:e
        r > limit ÷ d && return -1
        r *= d
    end
    return r
end

# z of the running product (held in `xz[n+1:2n]`) dotted with x of generator
# column `j` of `G`, unreduced. The z-workspace-by-x-column sibling of
# helper.jl's `dot_xz_ws_vs_col`, which pairs the other way round.
@inline function _dot_zws_xcol(xz::Vector{Int}, G::Matrix{Int}, n::Int, j::Int)
    acc = 0
    @turbo for q in 1:n
        acc += xz[n+q] * G[q, j]
    end
    return acc
end

# Right-multiply the running product P(xz[1:n], xz[n+1:2n], a) by generator
# column `j` of `G`, returning the new phase exponent.
#
# The cross term is oriented `z_left · x_right` to match the package's algebra,
# but inside a group walk the orientation cannot be observed: both factors lie
# in one abelian group, so their symplectic form vanishes and
# z_P · x_g ≡ x_P · z_g (mod d). What pins the X-before-Z convention here is the
# matrix element ⟨c + x| P |c⟩ = ζ^(a + s z·c) in `_emit_support` and
# `_add_pauli!`, and the tests break both on purpose.
@inline function _mul_generator!(xz::Vector{Int}, a::Int, G::Matrix{Int},
                                 j::Int, n::Int, d::Int, p::Int, s::Int)
    cross = _dot_zws_xcol(xz, G, n, j)    # read z before it changes
    a = mod(a + G[2n+1, j] + s * mod(cross, d), p)
    # `xz` is caller scratch and `G[:, j]` a tableau column: distinct arrays,
    # so `dst` and `src` cannot alias.
    addmul_mod!(xz, view(G, 1:(2n), j), 1, d)
    return a
end

# Call `f(xz, a)` once for each element of the group generated by columns
# `1:ngens` of `G`, the element being P(xz[1:n], xz[n+1:2n], a). `xz` is
# borrowed scratch, valid only during the call. `u` needs length `ngens`.
#
# A base-`d` odometer over the generator exponents, last digit fastest, starting
# from the identity. A step multiplies in each generator whose digit changes,
# including a wrapping one: `g_j^d = I` (odd d always; d = 2 once the caller has
# checked Hermiticity), so the multiplication that takes a digit from `d-1` back
# to `0` also returns that factor to the identity. Intermediate carry states are
# never emitted, and a carry off the most significant digit means every element
# has been visited. The generators commute, so right-multiplying in this order
# always yields the element whose exponents are `u`.
function _walk_group(f, G::Matrix{Int}, n::Int, ngens::Int, d::Int,
                     xz::Vector{Int}, u::Vector{Int})
    p = phase_modulus(d)
    s = p ÷ d
    fill!(xz, 0)
    fill!(u, 0)
    a = 0
    f(xz, a)
    ngens == 0 && return nothing
    while true
        j = ngens
        while true
            a = _mul_generator!(xz, a, G, j, n, d, p, s)
            u[j] += 1
            u[j] < d && break
            u[j] = 0
            j -= 1
            j == 0 && return nothing
        end
        f(xz, a)
    end
end

# Canonicalize a private copy of a pure tableau's stabilizers and derive what
# the support expansion needs. Returns `(G, k, cstar)`:
#
# - `G`, the reduced copy. Its columns `1:k` carry the X-block pivots in
#   increasing pivot row; columns `k+1:n` have an identically zero X block,
#   because `_canonicalize_tableau!` scans every X row before any Z row.
# - `k`, the X-pivot count, so the state has `d^k` support terms.
# - `cstar`, the lexicographically first support label.
#
# The caller's `stab`, `iscanonical` flag and workspaces are never touched.
function _prepare_support(tab::AbstractTableau)
    n, d = tab.n, tab.d
    p = phase_modulus(d)
    s = p ÷ d
    G = copy(tab.stab)
    pivcol = zeros(Int, 2n)
    xdotz = zeros(Int, n)
    _canonicalize_tableau!(G, n, n, d, true, tab.inversemod, pivcol, xdotz)

    k = 0
    for r in 1:n
        pivcol[r] != 0 && (k += 1)
    end

    # `b` solves every Z-only constraint a_j + s (z_j · b) ≡ 0 (mod p) at once:
    # a Z-only column has coefficient 1 at its own pivot qudit and 0 at every
    # other pivot, so with all non-pivot digits zero, z_j · b is just b[q_j].
    #
    # The division is exact. For odd d, s = 1. For d = 2 the column is Hermitian
    # with x = 0, so its phase is even -- and it is Hermitian although only the
    # ORIGINAL columns were checked, because canonicalization forms products of
    # commuting Hermitian Paulis, and (PQ)† = Q†P† = QP = PQ.
    b = zeros(Int, n)
    for q in 1:n
        j = pivcol[n+q]
        j == 0 && continue
        b[q] = mod(-(G[2n+1, j] ÷ s), d)
    end

    # cstar = b - Σ_j b[r_j] x_j. Commutation gives z_Z · x_j ≡ 0, so the shift
    # keeps every Z constraint; x_i[r_j] = δ_ij zeroes cstar at each X pivot.
    # Coefficients are read from `b`, never from the `cstar` being updated.
    cstar = copy(b)
    for r in 1:n
        j = pivcol[r]
        (j == 0 || b[r] == 0) && continue
        # `cstar` is local and `G[1:n, j]` a column of the copy: no aliasing.
        submul_mod!(cstar, view(G, 1:n, j), b[r], d)
    end
    return G, k, cstar
end

# Call `f(label, phase)` for each of the `d^k` support terms of a pure state,
# in strictly ascending lexicographic label order, the first being `cstar` with
# phase 0. `label` is borrowed scratch, valid only during the call.
#
# Walking the X generators with the last exponent fastest is lexicographic
# order on labels: if exponent vectors u and v first differ at j, every x_i
# with i >= j vanishes before row r_j and every x_i with i > j vanishes at it,
# so the labels agree before r_j and differ there by exactly u_j - v_j.
function _emit_support(f, G::Matrix{Int}, n::Int, k::Int, d::Int,
                       cstar::Vector{Int})
    p = phase_modulus(d)
    s = p ÷ d
    xz = zeros(Int, 2n)
    u = zeros(Int, k)
    label = zeros(Int, n)
    _walk_group(G, n, k, d, xz, u) do xz, a
        zc = 0
        for q in 1:n
            c = cstar[q] + xz[q]
            label[q] = c >= d ? c - d : c
            zc += xz[n+q] * cstar[q]
        end
        # g|cstar⟩ = ζ^a ω^(z·cstar) |cstar + x⟩ = ζ^(a + s z·cstar) |cstar + x⟩
        f(label, mod(a + s * mod(zc, d), p))
    end
    return nothing
end
